name: Deploy

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Install cargo-about
      run: cargo install --locked cargo-about
    
    - name: Build
      run: wasm-pack build --target web

    - name: Generate licenses
      run: cargo about generate about.hbs >license.html

    - name: Prepare web directory
      run: |
        mkdir web
        cp license.html web/
        cp index.html web/
        cp -r pkg web/pkg

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        command: pages deploy web --project-name webhasher
